#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: local-storage
#provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer
#
#---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-local-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Allows multiple pods to read and write
  persistentVolumeReclaimPolicy: Retain  # Adjust as needed
  storageClassName: local-storage
  local:
    path: /prometheus/local/directory
  nodeAffinity:  # Add this section
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k8sworker-1
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-local-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi  # Match the size to the PV's capacity

