apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      initContainers:
      - name: "init-datapath"
        image: centos:7
        command: ["chown", "-R", "65534:65534", "/grafana"]
        volumeMounts:
        - name: grafana-storage-volume
          mountPath: /grafana
          subPath: ""
      - name: "init-chmod"
        image: centos:7
        command: ["/bin/chmod","-R","777","/grafana"]
        volumeMounts:
        - name: grafana-storage-volume
          mountPath: /grafana
          subPath: ""
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests: 
            memory: 500M
            cpu: "500m"
        volumeMounts:
          - mountPath: /grafana
            name: grafana-storage-volume
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage-volume
          persistentVolumeClaim:
            claimName: grafana-local-pvc
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
      securityContext:
        runAsUser: 0